---
server:
  port: 8088
  contextPath: /MySpringBootStarterApp
---
spring:
  profiles: default
  active: default
datasource:
  springbootdemo:
    url: jdbc:h2:~/test
    username: sa
    password: sa
    driverClassName: org.h2.Driver
    defaultSchema:
    maxPoolSize: 10
    hibernate:
      hbm2ddl.method: create-drop
      show_sql: true
      format_sql: true
      dialect: org.hibernate.dialect.H2Dialect
---
spring:
  profiles: prod
  active: prod
datasource:
  springbootdemo:
    url: jdbc:mysql://localhost:3306/myspringbootstarterapp
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver
    defaultSchema:
    maxPoolSize: 20
    hibernate:
      hbm2ddl.method: update
      show_sql: true
      format_sql: true
      dialect: org.hibernate.dialect.MySQLDialect
